VAPID_PUBLIC_KEY = "BMpxzdUlGAtImtlyVht3Af0_Ck7SZjZpVGqbh_MwtBqckk4GJ0s_YoMj6qBtalgzAL5kL7HW_r-VfS5AxuAnDvI"
VAPID_PRIVATE_KEY = "-26zcP-aiRsYulOZcY4zG3KEv1WPU7kzI0uBEC0XYLc"
VAPID_CLAIM_EMAIL = "asdf@penis.de"
